# Generated by Django 3.2.7 on 2021-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoitem', models.CharField(max_length=800)),
                ('todoitem_fav', models.BooleanField()),
            ],
        ),
    ]
