# Generated by Django 3.2.7 on 2021-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0002_alter_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocat',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
