# Generated by Django 3.2.7 on 2021-10-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0003_alter_todocat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocat',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo3.todocat', to_field='name'),
        ),
    ]
