# Generated by Django 3.2.7 on 2021-10-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0004_alter_todolist_todo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=400)),
                ('cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo3.todolist')),
            ],
        ),
    ]
