# Generated by Django 3.2.7 on 2021-11-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0005_alter_todolist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todocat',
            name='selected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
