# Generated by Django 3.2.7 on 2022-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0006_todocat_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocat',
            name='selected',
            field=models.BooleanField(default=0),
        ),
    ]
