# Generated by Django 3.2.7 on 2021-10-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0008_alter_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocat',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='todo3.todocat', to_field='name'),
        ),
    ]
