# Generated by Django 3.2.7 on 2021-10-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0010_alter_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(blank=True, default='No category', on_delete=django.db.models.deletion.CASCADE, to='todo3.todocat', to_field='name'),
        ),
    ]
