# Generated by Django 3.2.7 on 2021-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0002_todolist_todoitem_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='todo_description',
            field=models.CharField(default='-', max_length=1000),
            preserve_default=False,
        ),
    ]
