# Generated by Django 3.2.7 on 2021-10-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo3', '0005_todocat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todocat',
            name='cat_fk',
        ),
        migrations.AddField(
            model_name='todolist',
            name='todo_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='todo3.todocat'),
            preserve_default=False,
        ),
    ]
